import type { Program } from "./types";

export const programs: Program[] = [
  {
    id: "prog-early-learners",
    slug: "early-learners",
    name: "Early Learners",
    kind: "core",
    ageLabel: "Ages 2–3",
    ageRange: "2–3",
    ageMinMonths: 24,
    ageMaxMonths: 35,
    stageIndex: 0,
    summary: "Exposure through listening, play, routine and repetition.",
    headline: "Little learners. Big discoveries.",
    value:
      "A warm, nurturing environment where your child explores, plays, and builds essential social, language, and motor skills.",
    imageKey: "earlyLearners",
    highlights: [
      { label: "Play & Exploration", icon: "blocks" },
      { label: "Language Development", icon: "chat" },
      { label: "Social Skills", icon: "person" },
      { label: "Movement & Motor Skills", icon: "motion" },
      { label: "Qur'an & Arabic Exposure", icon: "recitation" },
    ],
    gallery: [
      { imageKey: "earlyLearnersGallery0", caption: "Qur'an listening circle" },
      { imageKey: "earlyLearnersGallery1", caption: "Sensory and creative play" },
      { imageKey: "earlyLearnersGallery2", caption: "Outdoor play" },
    ],
    dayTitle: "A day in Early Learners",
    schedule: [
      { time: "8:00", label: "Arrival & Welcome", domains: "Social-Emotional" },
      { time: "8:30", label: "Morning Circle & Du‘a", domains: "Du‘a & Daily Practice" },
      { time: "9:00", label: "Qur'an Listening", domains: "Qur'an" },
      { time: "9:30", label: "Learning Centers", domains: "STEM · Creative Arts" },
      { time: "10:00", label: "Snack", domains: "Physical Development" },
      { time: "10:30", label: "Outdoor Play", domains: "Physical Development" },
      { time: "11:00", label: "Arabic Words & Rhymes", domains: "Arabic" },
      { time: "11:30", label: "Creative Activity", domains: "Creative Arts" },
      { time: "12:00", label: "Lunch", domains: "Social-Emotional" },
      { time: "12:45", label: "Rest / Quiet Time", domains: "Physical Development" },
      { time: "2:00", label: "Story & Islamic Manners", domains: "Islamic Studies · Akhlaq" },
      { time: "3:00", label: "Dismissal", domains: "Social-Emotional" },
    ],
    faqIds: ["el-toilet", "el-meals", "el-supplies", "el-teachers"],
    nextProgramId: "prog-preschool",
    gradeLabel: null,
  },
  {
    id: "prog-preschool",
    slug: "preschool",
    name: "Preschool",
    kind: "core",
    ageLabel: "Ages 3–4",
    ageRange: "3–4",
    ageMinMonths: 36,
    ageMaxMonths: 47,
    stageIndex: 1,
    summary: "Recognition and participation across every domain.",
    headline: "Growing curiosity, confidence and independence.",
    value:
      "A balanced, play-based program that builds early academic skills, social-emotional growth, and a love of learning.",
    imageKey: "preschool",
    highlights: [
      { label: "Early Literacy", icon: "book" },
      { label: "Early Math", icon: "grid" },
      { label: "Social-Emotional", icon: "heart" },
      { label: "Creative Arts", icon: "spark" },
      { label: "Qur'an & Arabic", icon: "recitation" },
    ],
    gallery: [
      { imageKey: "preschoolGallery0", caption: "Arabic circle time" },
      { imageKey: "preschoolGallery1", caption: "Learning centers" },
      { imageKey: "preschoolGallery2", caption: "Outdoor and movement" },
    ],
    dayTitle: "A day in Preschool",
    schedule: [
      { time: "8:00", label: "Arrival & Welcome", domains: "Social-Emotional" },
      { time: "8:30", label: "Circle Time & Du‘a", domains: "Du‘a & Daily Practice" },
      { time: "9:00", label: "Qur'an", domains: "Qur'an" },
      { time: "9:30", label: "Arabic", domains: "Arabic" },
      { time: "10:00", label: "Snack", domains: "Physical Development" },
      { time: "10:30", label: "Outdoor Play", domains: "Physical Development" },
      { time: "11:00", label: "Learning Centers", domains: "STEM" },
      { time: "11:30", label: "Math Activities", domains: "Mathematics" },
      { time: "12:00", label: "Lunch", domains: "Social-Emotional" },
      { time: "12:45", label: "Islamic Studies & Stories", domains: "Islamic Studies" },
      { time: "1:30", label: "Art / Creative Play", domains: "Creative Arts" },
      { time: "3:00", label: "Dismissal", domains: "Social-Emotional" },
    ],
    faqIds: ["ps-toilet", "ps-meals", "ps-supplies", "ps-teachers"],
    nextProgramId: "prog-pre-kindergarten",
    gradeLabel: null,
  },
  {
    id: "prog-pre-kindergarten",
    slug: "pre-kindergarten",
    name: "Pre-Kindergarten",
    kind: "core",
    ageLabel: "Ages 4–5",
    ageRange: "4–5",
    ageMinMonths: 48,
    ageMaxMonths: 59,
    stageIndex: 2,
    summary: "Structured learning and school readiness.",
    headline: "Ready for Kindergarten. Ready to grow.",
    value:
      "A purposeful, engaging program that builds strong academic, social, and independent learning skills for kindergarten success.",
    imageKey: "preK",
    highlights: [
      { label: "Literacy Readiness", icon: "book" },
      { label: "Math Foundations", icon: "grid" },
      { label: "Independence", icon: "person" },
      { label: "School Readiness", icon: "school" },
      { label: "Qur'an, Arabic & Islamic Studies", icon: "recitation" },
    ],
    gallery: [
      { imageKey: "preKGallery0", caption: "Qur'an small group" },
      { imageKey: "preKGallery1", caption: "STEM project" },
      { imageKey: "preKGallery2", caption: "Collaborative learning" },
    ],
    dayTitle: "A day in Pre-Kindergarten",
    schedule: [
      { time: "8:00", label: "Arrival & Morning Meeting", domains: "Social-Emotional" },
      { time: "8:30", label: "Qur'an", domains: "Qur'an" },
      { time: "9:00", label: "Arabic", domains: "Arabic" },
      { time: "9:30", label: "Literacy", domains: "English & Literacy" },
      { time: "10:00", label: "Snack", domains: "Physical Development" },
      { time: "10:30", label: "Outdoor Play", domains: "Physical Development" },
      { time: "11:00", label: "Mathematics", domains: "Mathematics" },
      { time: "11:30", label: "Islamic Studies", domains: "Islamic Studies" },
      { time: "12:00", label: "Lunch & Du‘a", domains: "Du‘a & Daily Practice" },
      { time: "12:45", label: "Science / STEM", domains: "Science · STEM" },
      { time: "1:45", label: "Creative Arts & Akhlaq", domains: "Creative Arts · Akhlaq" },
      { time: "3:00", label: "Dismissal", domains: "Social-Emotional" },
    ],
    faqIds: ["pk-toilet", "pk-meals", "pk-supplies", "pk-teachers"],
    nextProgramId: "prog-kindergarten",
    gradeLabel: null,
  },
  {
    id: "prog-kindergarten",
    slug: "kindergarten",
    name: "Kindergarten",
    kind: "core",
    ageLabel: "Ages 5–6",
    ageRange: "5–6",
    ageMinMonths: 60,
    ageMaxMonths: 71,
    stageIndex: 3,
    summary: "A full academic program: understanding, application, independence.",
    headline: "Building strong foundations for elementary school.",
    value:
      "A dynamic, academically rich program that nurtures confident, curious, and compassionate learners.",
    imageKey: "kindergarten",
    highlights: [
      { label: "Academic Foundations", icon: "book" },
      { label: "Critical Thinking", icon: "idea" },
      { label: "Islamic Character & Akhlaq", icon: "heart" },
      { label: "A Love of Learning", icon: "spark" },
      { label: "Qur'an, Arabic & Islamic Studies", icon: "recitation" },
    ],
    gallery: [
      { imageKey: "kindergartenGallery0", caption: "Qur'an recitation" },
      { imageKey: "kindergartenGallery1", caption: "Science and STEM" },
      { imageKey: "kindergartenGallery2", caption: "Reading and writing" },
    ],
    dayTitle: "A day in Kindergarten",
    schedule: [
      { time: "8:00", label: "Arrival & Morning Meeting", domains: "Social-Emotional" },
      { time: "8:30", label: "Qur'an", domains: "Qur'an" },
      { time: "9:00", label: "Arabic", domains: "Arabic" },
      { time: "9:30", label: "Literacy / Phonics", domains: "English & Literacy" },
      { time: "10:15", label: "Mathematics", domains: "Mathematics" },
      { time: "10:45", label: "Snack", domains: "Physical Development" },
      { time: "11:00", label: "Islamic Studies", domains: "Islamic Studies" },
      { time: "11:30", label: "Science / Social Studies", domains: "Science & Discovery" },
      { time: "12:00", label: "Lunch & Du‘a", domains: "Du‘a & Daily Practice" },
      { time: "12:45", label: "Art / STEM", domains: "Creative Arts · STEM" },
      { time: "1:45", label: "Enrichment & Akhlaq", domains: "Akhlaq" },
      { time: "3:00", label: "Dismissal", domains: "Social-Emotional" },
    ],
    faqIds: ["k-meals", "k-supplies", "k-homework", "k-teachers"],
    nextProgramId: null,
    gradeLabel: null,
  },
  {
    id: "prog-extended-learning",
    slug: "extended-learning",
    name: "Extended Learning",
    kind: "extended",
    ageLabel: "Before & After School · Summer · Ages 2–6",
    ageRange: "Before & After School · Summer · 2–6",
    ageMinMonths: 24,
    ageMaxMonths: 71,
    stageIndex: 3,
    summary:
      "Before School, After School and Summer Explorers — purposeful enrichment.",
    headline: "A longer day that still teaches.",
    value:
      "Enrichment at either end of the school day, plus Summer Explorers — a calm, purposeful start in the morning and afternoons of Qur’an practice, literacy, STEM and creative arts. Real support for working families, without turning the afternoon into waiting.",
    imageKey: "extendedLearning",
    highlights: [
      { label: "Before & After School", icon: "clock" },
      { label: "Qur'an & Literacy Practice", icon: "book" },
      { label: "STEM & Enrichment", icon: "blocks" },
      { label: "Creative Arts", icon: "spark" },
      { label: "Summer Explorers", icon: "spark" },
    ],
    gallery: [
      { imageKey: "extendedLearningGallery0", caption: "Reading corner" },
      { imageKey: "extendedLearningGallery1", caption: "Building and STEM" },
    ],
    dayTitle: "A day in Extended Learning",
    schedule: [
      { time: "Before", label: "Arrival & breakfast", domains: "Social-Emotional" },
      { time: "Before", label: "Quiet reading", domains: "English & Literacy" },
      { time: "Before", label: "Morning du‘a & greetings", domains: "Du‘a & Daily Practice" },
      { time: "Before", label: "Transition to the school day", domains: "Social-Emotional" },
      { time: "After", label: "Snack & outdoor play", domains: "Physical Development" },
      { time: "After", label: "Qur'an practice or Arabic games", domains: "Qur'an · Arabic" },
      { time: "After", label: "Reading, STEM or creative arts", domains: "Literacy · STEM · Creative Arts" },
      { time: "After", label: "Quiet choice time before pick-up", domains: "Social-Emotional" },
    ],
    faqIds: ["ext-signup", "ext-late", "ext-teachers"],
    nextProgramId: null,
    gradeLabel: null,
  },
  // Elementary grades are defined here so the model is complete, but they are
  // never shown while SiteSettings.elementaryActive is false.
  {
    id: "prog-grade-1",
    slug: "grade-1",
    name: "Grade 1",
    kind: "elementary",
    ageLabel: "Ages 6–7",
    ageRange: "6–7",
    ageMinMonths: 72,
    ageMaxMonths: 83,
    stageIndex: 3,
    summary: "",
    headline: "",
    value: "",
    imageKey: "elementary",
    highlights: [],
    gallery: [],
    dayTitle: "A day in Grade 1",
    schedule: [],
    faqIds: [],
    nextProgramId: null,
    gradeLabel: "Grade 1",
  },
];
